spring:
  datasource:
    url: jdbc:h2:file:~/social-media-management-api-sample
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

#  h2:
#    console:
#      enabled: true
#      path: /console

# This is for using a remote MySQL/Maria DB
# In Jelastic you may need a public IPv4
# Don't forget to add the MySQL driver to POM
#
#spring:
#  datasource:
#    url: jdbc:mysql://...
#    username: digibp
#    password: digibp
#    driverClassName: com.mysql.jdbc.Driver