/**
 * This file was generated by the JPA Modeler
 */
package ch.andreasmartin.smm.data.domain;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

/**
 * @author andreas.martin
 */
@Entity
public class Person implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String personName;

    @Basic
    private String email;

    @OneToMany(targetEntity = Tweet.class, mappedBy = "author")
    private List<Tweet> author;

    @OneToMany(targetEntity = Tweet.class, mappedBy = "reviewer")
    private List<Tweet> reviewer;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPersonName() {
        return this.personName;
    }

    public void setPersonName(String personName) {
        this.personName = personName;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public List<Tweet> getAuthor() {
        return this.author;
    }

    public void setAuthor(List<Tweet> author) {
        this.author = author;
    }

    public List<Tweet> getReviewer() {
        return this.reviewer;
    }

    public void setReviewer(List<Tweet> reviewer) {
        this.reviewer = reviewer;
    }

}
