/**
 * This file was generated by the JPA Modeler
 */
package ch.andreasmartin.smm.data.domain;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

/**
 * @author andreas.martin
 */
@Entity
public class Project implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String projectName;

    @OneToMany(targetEntity = Tweet.class, mappedBy = "project")
    private List<Tweet> tweet;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getProjectName() {
        return this.projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public List<Tweet> getTweet() {
        return this.tweet;
    }

    public void setTweet(List<Tweet> tweet) {
        this.tweet = tweet;
    }

}
