/**
 * This file was generated by the JPA Modeler
 */
package ch.andreasmartin.smm.data.domain;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * @author andreas.martin
 */
@Entity
public class Tweet implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String tweetText;

    @Basic
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date tweetDate;

    @Basic
    private String emailContent;

    @Basic
    private String comment;

    @Basic
    private boolean approved;

    @Basic
    private String review;

    @Basic
    private boolean revised;

    @OneToOne(targetEntity = Tweet.class)
    private Tweet originalTweet;

    @ManyToOne(targetEntity = Person.class)
    private Person author;

    @ManyToOne(targetEntity = Person.class)
    private Person reviewer;

    @ManyToOne(targetEntity = Project.class)
    private Project project;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTweetText() {
        return this.tweetText;
    }

    public void setTweetText(String tweetText) {
        this.tweetText = tweetText;
    }

    public Date getTweetDate() {
        return this.tweetDate;
    }

    public void setTweetDate(Date tweetDate) {
        this.tweetDate = tweetDate;
    }

    public String getEmailContent() {
        return this.emailContent;
    }

    public void setEmailContent(String emailContent) {
        this.emailContent = emailContent;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public boolean isApproved() {
        return this.approved;
    }

    public void setApproved(boolean approved) {
        this.approved = approved;
    }

    public String getReview() {
        return this.review;
    }

    public void setReview(String review) {
        this.review = review;
    }

    public boolean isRevised() {
        return this.revised;
    }

    public void setRevised(boolean revised) {
        this.revised = revised;
    }

    public Tweet getOriginalTweet() {
        return this.originalTweet;
    }

    public void setOriginalTweet(Tweet originalTweet) {
        this.originalTweet = originalTweet;
    }

    public Person getAuthor() {
        return this.author;
    }

    public void setAuthor(Person author) {
        this.author = author;
    }

    public Person getReviewer() {
        return this.reviewer;
    }

    public void setReviewer(Person reviewer) {
        this.reviewer = reviewer;
    }

    public Project getProject() {
        return this.project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

}
